### ISSUE TITLE
User-defined gas reporting

### ISSUE THREAD

**Issue by holic** [nomoixyz/vulcan#103]
Foundry's built in gas reports leave a lot to be desired. Often times what I want to test in terms of gas usage is not 1:1 with tests, so creating individual tests just for the purposes of making a call to determine gas usage feels a little silly.

In our recently overhaul of MUD internals, we've added our own gas report tooling [using a special `// !gasreport` line](https://github.com/search?q=repo%3Alatticexyz%2Fmud+%21gasreport&type=code) in our tests that wraps the next line in a `gasleft()` calculation, executes the test, and then [records the gas usage to a file](https://github.com/latticexyz/mud/blob/main/packages/store/gas-report.txt) that we check in and compare in each PR to see how gas is changing. This works but is very slow and clunky.

I'd love for some official Solidity gas reporting support, something along the lines of:
```solidity
function testBehavior() public {
  // calculates gas used by next line 
  reportGas('abi encode');
  abi.encode('hello world');

  // calculates gas within the start/end calls
  // block added for readability
  startReportGas('mint and burn');
  {
    mint();
    burn();
  }
  endReportGas();
}
```

Related:
- https://github.com/foundry-rs/foundry/issues/1795
- https://github.com/foundry-rs/foundry/issues/3766

**Comment by holic** [comment]
cc @alvrs @dk1a

**Comment by vdrg** [comment]
Thanks @holic.

I'm not sure how we could implement the first way you propose (report for next line) at the Vulcan layer. There might be ways we can come up with but for external calls only, which doesn't seem to be what you are looking for.

For the second method I'm sure we can figure something out. Are you proposing that we should write the report to a file or do you envision something more generic which users can later extend? For example, we could store a mapping of name -> gasUsed and then users can decide how to store the results (or log them), and we could also provide some opinionated ways of doing this.

Another alternative I'm thinking of, but only works for external calls, would be to integrate something like this into our "watchers" module, so you could do something like:

```solidity
address(myContract).watch();

myContract.doSomething();

expect(address(myContract).lastCall().gasUsed).toEqual(123);
// Or maybe
expect(address(myContract).lastCall()).toHaveSpentGas(123);
```

Thoughts?

**Comment by gnkz** [comment]
Closing this as this feature was added in #104
