### ISSUE TITLE
Research a way to use rust-ish Results on modules

### ISSUE THREAD

**Issue by gnkz** [nomoixyz/vulcan#144]
Some ideas:

- Each module can define their on Error types (Enums, custom errors, etc...)
- We need a way to handle these errors and identify the one that was used

```solidity
Result res = fs.open("...");
if (res.isError(FsError.FileDoesNotExist)) {
    // do something
}
```

- The result should be "unwrappable" and return the value with the corresponding type

```solidity
File file = fs.open("...").expect("Could not open file");
```

- A simple way to accomplish this is to define Result structs for each module and the corresponding expect/unwrap/etc. We could also create helpers to facilitate the creation of results in each module. This way there are not going to be any type conflicts and by using `using global` everything should work out of the box

**Comment by vdrg** [comment]
We ended up going for User Defined Types
