### ISSUE TITLE
Adding custom error messages to Except utils

### ISSUE THREAD

**Issue by mortimr** [nomoixyz/vulcan#229]
Hi !

I've been transitioning a test suite to `vulcan` and the only feature that I'm missing from the `forge-std` `Test` contract is the ability to specify a custom error message.
Ex:
```
assertEq(a, b, "a is not equal to b");
```
which was a really really nice feature as it really helped identify the exact failing condition

I was wondering if you would be open to extending the `Expect` utility to also have this feature with something like

```
expect(a).toEqual(b, "a is not equal to b")
```

Or something more exotic
```
because("a should be equal to b").expect(a).toEqual(b);
```

I could help implementing this, just lmk if it's something you think would fit in this library !

**Comment by gnkz** [comment]
Merged: #231
