### ISSUE TITLE
Console namespace tests

### ISSUE THREAD

**Issue by gnkz** [nomoixyz/vulcan#28]
Add tests for the `Console` namespace

**Comment by vdrg** [comment]
I'm not sure if we can actually test this, also just trying to test it might pollute the whole test suite with logs.

**Comment by gnkz** [comment]
we can ignore this for now till we figure out a good way to test this module

**Comment by gnkz** [comment]
Closing this since we are deprecating the `console` module in favor `forge-std/console2.sol`
